### ISSUE TITLE
More cryptocurrency?

### ISSUE THREAD

**Issue by Bitaltyn-project** [1btcxe/wlox-frontend#83]
How to add more cryptocurrency?

**Comment by mbassan** [comment]
You can't yet. We will deploy that capacity in the near future.

On Wed, Oct 28, 2015 at 9:40 AM, Bitaltyn-project notifications@github.com
wrote:

> How to add more cryptocurrency?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/1btcxe/wlox-frontend/issues/83.

## 

Moisés Bassan
Organic Technologies
moises@organic.com.pa
www.organic.com.pa
Tel: +507 6616-8671
Skype: moises.bassan
